version: "3.9"

services:
  db:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: python-de
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql

  mongodb:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: pythonde
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
